import { afterEach, describe, expect, it, vi } from "vitest";
import {
  decryptUpworkClientSecret,
  encryptUpworkClientSecret,
} from "./upwork-client-secret";

const KEY = "0".repeat(63) + "1";

/**
 * Generated by the original hand-rolled implementation, before the crypto was
 * extracted into `secret-box.ts`.
 *
 * This is the whole point of the file. Every self-hoster has Upwork client
 * secrets already encrypted in their database under that implementation; if the
 * extraction changed the wire format by so much as a byte, those secrets become
 * undecryptable and every affected user has to re-register their Upwork app
 * with no error message explaining why.
 */
const LEGACY_PAYLOAD =
  "v1:nYMwUmV75-q705goCnKV-Q:MP7r9Psv72L9_Eu28HNMvw:vtoPsxnIBUnujHlcU5m0BQDb2w";
const LEGACY_PLAINTEXT = "upwork-secret-value";

afterEach(() => {
  vi.unstubAllEnvs();
});

describe("Upwork client secret encryption", () => {
  it("still decrypts a secret stored by the pre-extraction implementation", () => {
    vi.stubEnv("UPWORK_CREDENTIALS_ENCRYPTION_KEY", KEY);
    expect(decryptUpworkClientSecret(LEGACY_PAYLOAD)).toBe(LEGACY_PLAINTEXT);
  });

  it("round-trips", () => {
    vi.stubEnv("UPWORK_CREDENTIALS_ENCRYPTION_KEY", KEY);
    const payload = encryptUpworkClientSecret("new-secret");
    expect(decryptUpworkClientSecret(payload)).toBe("new-secret");
  });

  it("reads its own env var, not another module's", () => {
    vi.stubEnv("UPWORK_CREDENTIALS_ENCRYPTION_KEY", "");
    vi.stubEnv("AI_KEYS_ENCRYPTION_KEY", KEY);
    expect(() => encryptUpworkClientSecret("x")).toThrow(
      /UPWORK_CREDENTIALS_ENCRYPTION_KEY/,
    );
  });
});
